# run creation.sql first
USE bank_of_words_db;

insert into users (user_id, username, password_hash, email) VALUES (1, 'admin', '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5', '');

INSERT INTO tables (table_id, creator_id, table_name) VALUES (1, 1, 'English: easy');
INSERT INTO tables (table_id, creator_id, table_name) VALUES (2, 1, 'English: medium');
INSERT INTO tables (table_id, creator_id, table_name) VALUES (3, 1, 'Georgian - English');

# English: easy
INSERT INTO words (word, definition, table_id) VALUES   ('more', 'A greater or additional amount or degree.', 1),
                                                        ('day', 'A period of twenty-four hours as a unit of time, reckoned from one midnight to the next, corresponding to a rotation of the earth on its axis.', 1),
                                                        ('could', 'Used to indicate possibility.', 1),
                                                        ('go', 'Move from one place to another; travel.', 1),
                                                        ('come', 'Move or travel toward or into a place thought of as near or familiar to the speaker.', 1),
                                                        ('did', 'Past tense of the verb "do".', 1),
                                                        ('number', 'An arithmetical value, expressed by a word, symbol, or figure, representing a particular quantity and used in counting and making calculations and for showing order in a series or for identification.', 1),
                                                        ('sound', 'Vibrations that travel through the air or another medium and can be heard when they reach a person\'s or animal\'s ear.', 1),
                                                        ('no', 'Not any.', 1),
                                                        ('most', 'Greatest in amount or degree.', 1),
                                                        ('people', 'Human beings in general or considered collectively.', 1),
                                                        ('my', 'Belonging to or associated with the speaker.', 1),
                                                        ('over', 'Extending directly upward from.', 1),
                                                        ('know', 'Be aware of through observation, inquiry, or information.', 1),
                                                        ('water', 'A colorless, transparent, odorless, tasteless liquid that forms the seas, lakes, rivers, and rain and is the basis of the fluids of living organisms.', 1),
                                                        ('than', 'Used to introduce the second element in a comparison.', 1),
                                                        ('call', 'Give (an infant or animal) a specified name.', 1),
                                                        ('first', 'Coming before all others in time or order; earliest; 1st.', 1),
                                                        ('who', 'Used to introduce a question about the identity or nature of a person or thing.', 1),
                                                        ('may', 'Expressing possibility.', 1),
                                                        ('down', 'Toward or in a lower place or position.', 1),
                                                        ('side', 'A position to the left or right of an object, place, or central point.', 1),
                                                        ('been', 'Past participle of the verb "be".', 1),
                                                        ('now', 'At the present time or moment.', 1),
                                                        ('find', 'Discover or perceive by chance or unexpectedly.', 1),
                                                        ('any', 'Used to refer to one or some of a thing or number of things, no matter how much or how many.', 1),
                                                        ('new', 'Not existing before; made, introduced, or discovered recently or now for the first time.', 1),
                                                        ('work', 'Activity involving mental or physical effort done in order to achieve a purpose or result.', 1),
                                                        ('part', 'A piece or segment of something such as an object, activity, or period of time, which combined with other pieces makes up the whole.', 1),
                                                        ('take', 'Reach for and hold with one\'s hands; capture or gain possession of by force or skill.', 1),
                                                        ('get', 'Come to have or hold (something); receive.', 1),
                                                        ('place', 'A particular position or point in space.', 1),
                                                        ('made', 'Past and past participle of the verb "make".', 1),
                                                        ('live', 'Remain alive.', 1),
                                                        ('where', 'In or to what place or position.', 1),
                                                        ('after', 'Denoting the time following an event or another specified time.', 1),
                                                        ('back', 'In or to the place or situation that someone or something came from.', 1),
                                                        ('little', 'Small in size, amount, or degree.', 1),
                                                        ('only', 'And no one or nothing more besides; solely or exclusively.', 1),
                                                        ('round', 'Shaped like or approximately like a circle or cylinder.', 1),
                                                        ('man', 'An adult human male.', 1),
                                                        ('year', 'The time taken by a planet to make one revolution around the sun.', 1),
                                                        ('came', 'Past tense of the verb "come".', 1),
                                                        ('show', 'Be, allow, or cause to be visible; display.', 1),
                                                        ('every', 'Used to refer to all the individual members or things in a particular group or quantity.', 1),
                                                        ('good', 'To be desired or approved of.', 1),
                                                        ('me', 'Used by a speaker to refer to themselves as the object of a verb or preposition.', 1),
                                                        ('give', 'Freely transfer the possession of (something) to (someone); hand over to.', 1),
                                                        ('our', 'Belonging to or associated with the speaker and one or more other people previously mentioned or easily identified.', 1),
                                                        ('under', 'Extending or directly below something else.', 1),
                                                        ('name', 'A word or set of words by which a person, animal, place, or thing is known, addressed, or referred to.', 1),
                                                        ('very', 'Used to emphasize an adjective or adverb.', 1),
                                                        ('through', 'Moving in one side and out of the other side of (an opening, channel, or location).', 1),
                                                        ('just', 'Based on or behaving according to what is morally right and fair.', 1),
                                                        ('form', 'The visible shape or configuration of something.', 1),
                                                        ('sentence', 'A set of words that is complete in itself, typically containing a subject and predicate, conveying a statement, question, exclamation, or command, and consisting of a main clause and sometimes one or more subordinate clauses.', 1),
                                                        ('great', 'Of an extent, amount, or intensity considerably above average.', 1),
                                                        ('think', 'Have a particular opinion, belief, or idea about someone or something.', 1),
                                                        ('say', 'Utter words so as to convey information, an opinion, a feeling or intention, or an instruction.', 1),
                                                        ('help', 'Make it easier or possible for (someone) to do something by offering them one\'s services or resources.', 1),
                                                        ('low', 'Of less than average height from top to bottom or to the top from the ground.', 1),
                                                        ('line', 'A long, narrow mark or band.', 1),
                                                        ('differ', 'Be unlike or dissimilar.', 1),
                                                        ('turn', 'Move in a circular direction wholly or partly around an axis or point.', 1),
                                                        ('cause', 'A person or thing that gives rise to an action, phenomenon, or condition.', 1),
                                                        ('much', 'A large amount or extent.', 1),
                                                        ('mean', 'Intend to convey, indicate, or refer to (a particular thing or notion); signify.', 1),
                                                        ('before', 'During the period of time preceding (a particular event or time).', 1),
                                                        ('move', 'Go in a specified direction or manner; change position.', 1),
                                                        ('right', 'In accordance with what is good, proper, or just.', 1),
                                                        ('boy', 'A male child or young man.', 1),
                                                        ('old', 'Having lived for a long time; no longer young.', 1),
                                                        ('too', 'To a higher degree than is desirable, permissible, or possible; excessively.', 1),
                                                        ('same', 'Identical; not different or changed.', 1),
                                                        ('tell', 'Communicate information, facts, or news to someone in spoken or written words.', 1),
                                                        ('does', 'Third person singular present of the verb "do".', 1),
                                                        ('set', 'Put, lay, or stand (something) in a specified place or position.', 1),
                                                        ('three', 'Equivalent to the sum of one and two; one more than two; 3.', 1),
                                                        ('want', 'Have a desire to possess or do (something); wish for.', 1),
                                                        ('air', 'The invisible gaseous substance surrounding the earth, a mixture mainly of oxygen and nitrogen.', 1),
                                                        ('well', 'In a good or satisfactory way.', 1),
                                                        ('also', 'In addition; too.', 1),
                                                        ('play', 'Engage in activity for enjoyment and recreation rather than a serious or practical purpose.', 1),
                                                        ('small', 'Of a size that is less than normal or usual.', 1),
                                                        ('end', 'A final part of something, especially a period of time, an activity, or a story.', 1),
                                                        ('put', 'Move to or place in a particular position.', 1),
                                                        ('home', 'The place where one lives permanently, especially as a member of a family or household.', 1),
                                                        ('read', 'Look at and comprehend the meaning of (written or printed matter) by mentally interpreting the characters or symbols of which it is composed.', 1),
                                                        ('hand', 'The end part of a person\'s arm beyond the wrist, including the palm, fingers, and thumb.', 1),
                                                        ('port', 'A town or city with a harbor where ships load or unload, especially one where customs officers are stationed.', 1),
                                                        ('large', 'Of considerable or relatively great size, extent, or capacity.', 1),
                                                        ('spell', 'Write or name the letters that form (a word) in correct sequence.', 1),
                                                        ('add', 'Join (something) to something else so as to increase the size, number, or amount.', 1),
                                                        ('even', 'Used to emphasize something surprising or extreme.', 1),
                                                        ('land', 'The part of the earth\'s surface that is not covered by water, as opposed to the sea or the air.', 1),
                                                        ('here', 'In, at, or to this place or position.', 1),
                                                        ('must', 'Be obliged to; should (expressing necessity).', 1),
                                                        ('big', 'Of considerable size or extent.', 1),
                                                        ('high', 'Of great vertical extent.', 1),
                                                        ('such', 'Of the type previously mentioned or inferred.', 1),
                                                        ('follow', 'Go or come after (a person or thing proceeding ahead); move or travel behind.', 1),
                                                        ('act', 'Take action; do something.', 1),
                                                        ('why', 'For what reason or purpose.', 1),
                                                        ('ask', 'Say something in order to obtain an answer or information.', 1),
                                                        ('men', 'Plural form of "man", an adult human male.', 1),
                                                        ('change', 'Make or become different.', 1),
                                                        ('went', 'Past tense of the verb "go".', 1),
                                                        ('light', 'The natural agent that stimulates sight and makes things visible.', 1),
                                                        ('kind', 'A group of people or things having similar characteristics.', 1),
                                                        ('off', 'Away from the place in question; to or at a distance.', 1),
                                                        ('need', 'Require (something) because it is essential or very important.', 1),
                                                        ('house', 'A building for human habitation, especially one that is lived in by a family or small group of people.', 1),
                                                        ('picture', 'A painting, drawing, photograph, or other representation of a person or thing.', 1),
                                                        ('try', 'Make an attempt or effort to do something.', 1),
                                                        ('us', 'Used by a speaker to refer to himself or herself and one or more other people as the object of a verb or preposition.', 1),
                                                        ('again', 'Once more; another time.', 1),
                                                        ('animal', 'A living organism that feeds on organic matter, typically having specialized sense organs and nervous system and able to respond rapidly to stimuli.', 1),
                                                        ('point', 'A particular spot, place, or position in an area or on a map, object, or surface.', 1),
                                                        ('mother', 'A woman in relation to her child or children.', 1),
                                                        ('world', 'The earth, together with all of its countries, peoples, and natural features.', 1),
                                                        ('near', 'At or to a short distance away; nearby.', 1),
                                                        ('build', 'Construct (something, typically a building, road, or machine).', 1),
                                                        ('self', 'A \'s essential being that distinguishes them from others, especially considered as the object of introspection or reflexive action.', 1),
                                                        ('earth', 'The planet on which we live; the world.', 1),
                                                        ('father', 'A man in relation to his child or children.', 1),
                                                        ('head', 'The upper part of the human body, or the front or upper part of the body of an animal, typically separated from the rest of the body by a neck, and containing the brain, mouth, and sense organs.', 1),
                                                        ('stand', 'Have or maintain an upright position, supported by one\'s feet.', 1),
                                                        ('own', 'Belonging to oneself or itself; typically used to emphasize the fact of ownership.', 1),
                                                        ('page', 'One side of a sheet of paper in a collection of bound sheets, especially as a child\'s drawing or a printed or written document.', 1),
                                                        ('should', 'Used to indicate obligation, duty, or correctness, typically when criticizing someone\'s actions.', 1),
                                                        ('country', 'A nation with its own government, occupying a particular territory.', 1),
                                                        ('found', 'Past and past participle of the verb "find".', 1),
                                                        ('answer', 'A thing said, written, or done to deal with or as a reaction to a question, statement, or situation.', 1),
                                                        ('school', 'An institution for educating children.', 1),
                                                        ('grow', 'Undergo natural development by increasing in size and changing physically; progress to maturity.', 1),
                                                        ('study', 'The devotion of time and attention to acquiring knowledge on an academic subject, especially by means of books.', 1),
                                                        ('still', 'Up to and including the present or the time mentioned; even now (or then) as formerly.', 1),
                                                        ('learn', 'Gain or acquire knowledge of or skill in (something) by study, experience, or being taught.', 1),
                                                        ('plant', 'A living organism of the kind exemplified by trees, shrubs, herbs, grasses, ferns, and mosses, typically growing in a permanent site, absorbing water and inorganic substances through its roots, and synthesizing nutrients in its leaves by photosynthesis using the green pigment chlorophyll.', 1),
                                                        ('cover', 'Put something on top of or in front of (something) in order to protect or conceal it.', 1),
                                                        ('food', 'Any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth.', 1),
                                                        ('sun', 'The star around which the earth orbits, providing light and heat to the earth.', 1),
                                                        ('four', 'Equivalent to the sum of two and two; one more than three; 4.', 1),
                                                        ('between', 'At, into, or across the space separating (two objects or regions).', 1),
                                                        ('state', 'The particular condition that someone or something is in at a specific time.', 1),
                                                        ('keep', 'Have or retain possession of.', 1),
                                                        ('eye', 'Each of a pair of globular organs of sight in the head of humans and vertebrate animals.', 1),
                                                        ('never', 'At no time in the past or future; on no occasion; not ever.', 1),
                                                        ('last', 'Coming after all others in time or order; final.', 1),
                                                        ('let', 'Not prevent or forbid; allow.', 1),
                                                        ('thought', 'An idea or opinion produced by thinking or occurring suddenly in the mind.', 1),
                                                        ('city', 'A large town.', 1),
                                                        ('tree', 'A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground.', 1),
                                                        ('cross', 'Go or extend across or to the other side of (a path, road, stretch of water, or area).', 1),
                                                        ('farm', 'An area of land and its buildings used for growing crops and rearing animals, typically under the control of one owner or manager.', 1),
                                                        ('hard', 'Solid, firm, and rigid; not easily broken, bent, or pierced.', 1),
                                                        ('start', 'Begin or be reckoned from a particular point in time or space; come into being.', 1),
                                                        ('might', 'Used to express possibility or make a suggestion or request.', 1),
                                                        ('story', 'An account of imaginary or real people and events told for entertainment.', 1),
                                                        ('saw', 'Past tense of the verb "see".', 1),
                                                        ('far', 'At, to, or by a great distance (used to indicate the extent to which one thing or person is distant from another).', 1),
                                                        ('sea', 'The expanse of saltwater that covers most of the earth\'s surface and surrounds its landmasses.', 1),
                                                        ('draw', 'Produce (a picture or diagram) by making lines and marks on paper with a pencil, pen, etc.', 1),
                                                        ('left', 'On, toward, or relating to the side of a human body or of a thing that is to the west when the person or thing is facing north.', 1),
                                                        ('late', 'Doing something or taking place after the expected, proper, or usual time.', 1),
                                                        ('run', 'Move at a speed faster than a walk, never having both or all the feet on the ground at the same time.', 1),
                                                        ('don\'t', 'Do not; does not.', 1),
                                                        ('while', 'During the time that; at the same time as.', 1),
                                                        ('press', 'Exert continuous physical force on (something, 1), typically with one\'s hands.', 1),
                                                        ('close', 'Only a short distance away or apart in space or time.', 1),
                                                        ('night', 'The period of darkness in each twenty-four hours; the time from sunset to sunrise.', 1),
                                                        ('real', 'Actually existing as a thing or occurring in fact; not imagined or supposed.', 1),
                                                        ('life', 'The condition that distinguishes animals and plants from inorganic matter, including the capacity for growth, reproduction, functional activity, and continual change preceding death.', 1),
                                                        ('few', 'A small number of something; not many.', 1),
                                                        ('north', 'The direction in which a compass needle normally points, toward the horizon on the left-hand side of a person facing east, or the part of the world lying in this direction.', 1),
                                                        ('open', 'Allowing access, passage, or a view through an empty space; not closed or blocked up.', 1),
                                                        ('seem', 'Give the impression or sensation of being something or having a particular quality.', 1),
                                                        ('together', 'With or in proximity to another person or people.', 1),
                                                        ('next', 'Coming immediately after the present one in order, rank, or space.', 1),
                                                        ('white', 'Of the color of milk or fresh snow, due to the reflection of all visible rays of light; the opposite of black.', 1),
                                                        ('children', 'Plural form of child, a young human being below the age of puberty or below the legal age of majority.', 1),
                                                        ('begin', 'Perform or undergo the first part of (an action or activity).', 1),
                                                        ('got', 'Past tense of get, come to have or hold (something); receive.', 1),
                                                        ('walk', 'Move at a regular and fairly slow pace by lifting and setting down each foot in turn, never having both feet off the ground at once.', 1),
                                                        ('example', 'A thing characteristic of its kind or illustrating a general rule.', 1),
                                                        ('ease', 'Freedom from pain, discomfort, or anxiety.', 1),
                                                        ('paper', 'Material manufactured in thin sheets from the pulp of wood or other fibrous substances, used for writing, drawing, or printing on, or as wrapping material.', 1),
                                                        ('group', 'A number of people or things that are located, gathered, or classed together.', 1),
                                                        ('always', 'At all times; on all occasions.', 1),
                                                        ('music', 'Vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion.', 1),
                                                        ('those', 'Plural form of that, used to identify a specific person or thing observed or heard by the speaker.', 1),
                                                        ('both', 'Used to refer to two people or things, regarded and identified together.', 1),
                                                        ('mark', 'A small area on a surface having a different color from its surroundings, typically one caused by damage or dirt.', 1),
                                                        ('often', 'Frequently; many times.', 1),
                                                        ('letter', 'A character representing one or more of the sounds used in speech; any of the symbols of an alphabet.', 1),
                                                        ('until', 'Up to (the point in time or the event mentioned).', 1),
                                                        ('mile', 'A unit of linear measure equal to 5,280 feet (approximately 1.609 kilometers).', 1),
                                                        ('river', 'A large natural stream of water flowing in a channel to the sea, a lake, or another such stream.', 1),
                                                        ('car', 'A road vehicle, typically with four wheels, powered by an internal combustion engine and able to carry a small number of people.', 1),
                                                        ('feet', 'Plural form of foot, the lower extremity of the leg below the ankle, on which a person stands or walks.', 1),
                                                        ('care', 'The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something.', 1),
                                                        ('second', 'Equal to one-sixtieth of a minute.', 1),
                                                        ('book', 'A written or printed work consisting of pages glued or sewn together along one side and bound in covers.', 1),
                                                        ('carry', 'Support and move (someone or something) from one place to another.', 1),
                                                        ('took', 'Past tense of take, lay hold of (something) with one\'s hands; reach for and hold.', 1),
                                                        ('science', 'The intellectual and practical activity encompassing the systematic study of the structure and behavior of the physical and natural world through observation and experiment.', 1),
                                                        ('eat', 'Put (food) into the mouth and chew and swallow it.', 1),
                                                        ('room', 'A space that can be occupied or where something can be done, especially viewed in terms of whether there is enough.', 1),
                                                        ('friend', 'A person with whom one has a bond of mutual affection, typically one exclusive of sexual or family relations.', 1),
                                                        ('began', 'Past tense of begin, start; perform or undergo the first part of (an action or activity).', 1),
                                                        ('idea', 'A thought or suggestion as to a possible course of action.', 1),
                                                        ('fish', 'A limbless cold-blooded vertebrate animal with gills and fins and living wholly in water.', 1),
                                                        ('mountain', 'A large natural elevation of the earth\'s surface rising abruptly from the surrounding level; a large steep hill.', 1),
                                                        ('stop', 'Cease or cause to cease moving or operating.', 1),
                                                        ('once', 'On one occasion or for one time only.', 1),
                                                        ('base', 'The lowest part or edge of something, especially the part on which it rests or is supported.', 1),
                                                        ('hear', 'Perceive with the ear the sound made by (someone or something).', 1),
                                                        ('horse', 'A large plant-eating domesticated mammal with solid hoofs and a flowing mane and tail, used for riding, racing, and to carry and pull loads.', 1),
                                                        ('cut', 'Make an opening, incision, or wound in (something) with a sharp-edged tool or object.', 1),
                                                        ('sure', 'Certain to happen; inevitable.', 1),
                                                        ('watch', 'Look at or observe attentively over a period of time.', 1),
                                                        ('color', 'The property possessed by an object of producing different sensations on the eye as a result of the way it reflects or emits light.', 1),
                                                        ('face', 'The front part of a person\'s head from the forehead to the chin, or the corresponding part in an animal.', 1),
                                                        ('wood', 'The hard fibrous material that forms the main substance of the trunk or branches of a tree or shrub.', 1),
                                                        ('main', 'Chief in size or importance.', 1),
                                                        ('enough', 'As much or as many as required.', 1),
                                                        ('plain', 'Not decorated or elaborate; simple or basic in character.', 1),
                                                        ('girl', 'A female child.', 1),
                                                        ('usual', 'Customary; normal; habitual.', 1),
                                                        ('young', 'Having lived or existed for only a short time.', 1),
                                                        ('ready', 'Prepared for an activity or situation; willing to do something.', 1),
                                                        ('above', 'At a higher level or layer than.', 1),
                                                        ('ever', 'At any time.', 1),
                                                        ('red', 'Of a color at the end of the spectrum next to orange and opposite violet, as of blood, fire, or rubies.', 1),
                                                        ('list', 'A number of connected items or names written or printed consecutively, typically one below the other.', 1),
                                                        ('though', 'Despite the fact that; although.', 1),
                                                        ('feel', 'Perceive or be aware of a physical sensation or emotional state.', 1),
                                                        ('talk', 'Speak in order to give information or express ideas or feelings; converse or communicate by spoken words.', 1),
                                                        ('bird', 'A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak and (typically) by being able to fly.', 1),
                                                        ('soon', 'In or after a short time.', 1),
                                                        ('body', 'The physical structure, including the bones, flesh, and organs, of a person or an animal.', 1),
                                                        ('dog', 'A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking, howling, or whining voice.', 1),
                                                        ('family', 'A group consisting of parents and children living together in a household.', 1),
                                                        ('direct', 'Control the operations of; manage or govern.', 1),
                                                        ('pose', 'Present or constitute (a problem, danger, or difficulty).', 1),
                                                        ('leave', 'Go away from.', 1),
                                                        ('song', 'A short poem or other set of words set to music or meant to be sung.', 1),
                                                        ('measure', 'Ascertain the size, amount, or degree of (something) by using an instrument or device marked in standard units or by comparing it with an object of known size.', 1),
                                                        ('door', 'A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle, or in the framework of a cupboard.', 1),
                                                        ('product', 'An article or substance that is manufactured or refined for sale.', 1),
                                                        ('black', 'Of the very darkest color; the opposite of white.', 1),
                                                        ('short', 'Measuring a small distance from end to end.', 1),
                                                        ('numeral', 'A figure, symbol, or group of these denoting a number.', 1),
                                                        ('class', 'A set or category of things having some property or attribute in common and differentiated from others by kind, type, or quality.', 1),
                                                        ('wind', 'The perceptible natural movement of the air, especially in the form of a current blowing from a particular direction.', 1),
                                                        ('question', 'A sentence worded or expressed so as to elicit information.', 1),
                                                        ('happen', 'Take place; occur.', 1),
                                                        ('complete', 'Having all the necessary or appropriate parts.', 1),
                                                        ('ship', 'A large seagoing vessel.', 1),
                                                        ('area', 'A region or part of a town, a country, or the world.', 1),
                                                        ('half', 'Either of two equal or corresponding parts into which something is or can be divided.', 1),
                                                        ('rock', 'The solid mineral material forming part of the surface of the earth and other similar planets, exposed on the surface or underlying the soil or oceans.', 1),
                                                        ('order', 'The arrangement or disposition of people or things in relation to each other according to a particular sequence, pattern, or method.', 1),
                                                        ('fire', 'A process in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke.', 1),
                                                        ('south', 'The direction towards the point of the horizon 90 degrees clockwise from east, or the point on the horizon itself.', 1),
                                                        ('problem', 'A matter or situation regarded as unwelcome or harmful and needing to be dealt with and overcome.', 1),
                                                        ('piece', 'A portion of an object or of material, produced by cutting, tearing, or breaking the whole.', 1),
                                                        ('told', 'Past tense of tell, communicate information, facts, or news to someone in spoken or written words.', 1),
                                                        ('knew', 'Past tense of know, have developed a relationship with (someone) through meeting and spending time with them; be familiar or friendly with.', 1),
                                                        ('pass', 'Move or cause to move in a specified direction.', 1),
                                                        ('since', 'In the intervening period between (the time mentioned) and the time under consideration, typically the present.', 1),
                                                        ('top', 'The highest or uppermost point, part, or surface of something.', 1),
                                                        ('whole', 'All of; entire; complete.', 1),
                                                        ('king', 'The male ruler of an independent state, especially one who inherits the position by right of birth.', 1),
                                                        ('space', 'A continuous area or expanse that is free, available, or unoccupied.', 1),
                                                        ('heard', 'Past tense of hear, perceive with the ear the sound made by (someone or something).', 1),
                                                        ('best', 'Of the most excellent, effective, or desirable type or quality.', 1),
                                                        ('hour', 'A period of time equal to a twenty-fourth part of a day and night and divided into 60 minutes.', 1),
                                                        ('better', 'Of a more excellent or effective type or quality.', 1),
                                                        ('true', 'In accordance with fact or reality; accurate or exact.', 1),
                                                        ('during', 'Throughout the course or duration of (a period of time).', 1),
                                                        ('hundred', 'The number equivalent to the product of ten and ten; ten more than ninety; 100.', 1),
                                                        ('five', 'Equivalent to the sum of two and three; one more than four, or half of ten; 5.', 1),
                                                        ('remember', 'Have in or be able to bring to one\'s mind an awareness of (someone or something from the past).', 1),
                                                        ('step', 'Lift and set down one\'s foot or one foot after the other in order to walk or move to a new position.', 1),
                                                        ('early', 'Happening or done before the usual or expected time.', 1),
                                                        ('hold', 'Grasp, carry, or support with one\'s arms or hands.', 1),
                                                        ('west', 'The direction towards the point of the horizon 90 degrees clockwise from south, or the part of the world lying in this direction.', 1),
                                                        ('ground', 'The solid surface of the earth.', 1),
                                                        ('interest', 'The state of wanting to know or learn about something or someone.', 1),
                                                        ('reach', 'Stretch out an arm in a specified direction in order to touch or grasp something.', 1),
                                                        ('fast', 'Moving or capable of moving at high speed.', 1),
                                                        ('verb', 'A word used to describe an action, occurrence, or state of being.', 1),
                                                        ('sing', 'Produce musical sounds with the voice, especially words with a set tune.', 1),
                                                        ('listen', 'Give one\'s attention to a sound.', 1),
                                                        ('six', 'Equivalent to the sum of three and three; one more than five, or half of twelve; 6.', 1),
                                                        ('table', 'A piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working at.', 1),
                                                        ('travel', 'Make a journey, typically of some length or abroad.', 1),
                                                        ('less', 'Smaller in amount, degree, or size.', 1),
                                                        ('morning', 'The period of time between midnight and noon, especially from sunrise to noon.', 1),
                                                        ('simple', 'Easily understood or done; presenting no difficulty.', 1),
                                                        ('several', 'More than two but not many.', 1),
                                                        ('vowel', 'A speech sound produced by the vocal cords with relatively little obstruction of the oral and pharyngeal cavities.', 1),
                                                        ('toward', 'In the direction of.', 1),
                                                        ('war', 'A state of armed conflict between different nations or states or different groups within a nation or state.', 1),
                                                        ('lay', 'Put down, especially gently or carefully.', 1),
                                                        ('against', 'In opposition to; contrary to.', 1),
                                                        ('pattern', 'A repeated decorative design.', 1),
                                                        ('slow', 'Moving or operating, or designed to do so, only at a low speed; not quick or fast.', 1),
                                                        ('center', 'The middle point or part.', 1),
                                                        ('love', 'An intense feeling of deep affection.', 1),
                                                        ('person', 'A human being regarded as an individual.', 1),
                                                        ('money', 'A current medium of exchange in the form of coins and banknotes; coins and banknotes collectively.', 1),
                                                        ('serve', 'Perform duties or services for (another person or an organization).', 1),
                                                        ('appear', 'Come into sight; become visible or noticeable, typically without visible agent or apparent cause.', 1),
                                                        ('road', 'A wide way leading from one place to another, especially one with a specially prepared surface that vehicles can use.', 1),
                                                        ('map', 'A diagrammatic representation of an area of land or sea showing physical features, cities, roads, etc.', 1),
                                                        ('rain', 'Moisture condensed from the atmosphere that falls visibly in separate drops.', 1),
                                                        ('rule', 'One of a set of explicit or understood regulations or principles governing conduct or procedure within a particular area of activity.', 1),
                                                        ('govern', 'Conduct the policy, actions, and affairs of (a state, organization, or people).', 1),
                                                        ('pull', 'Exert force on (someone or something) so as to cause movement towards oneself.', 1),
                                                        ('cold', 'Of or at a low or relatively low temperature, especially when compared with the human body.', 1),
                                                        ('notice', 'Become aware of; pay attention to.', 1),
                                                        ('voice', 'The sound produced in a person\'s larynx and uttered through the mouth, as speech or song.', 1),
                                                        ('energy', 'The strength and vitality required for sustained physical or mental activity.', 1),
                                                        ('hunt', 'Pursue and kill (a wild animal) for sport or food.', 1),
                                                        ('probable', 'Likely to happen or be the case.', 1),
                                                        ('bed', 'A piece of furniture for sleep or rest, typically a framework with a mattress and coverings.', 1),
                                                        ('brother', 'A man or boy in relation to other sons and daughters of his parents.', 1),
                                                        ('egg', 'An oval or round object laid by a female bird, reptile, fish, or invertebrate, usually containing a developing embryo.', 1);
